name: Terraform Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Get Public IP
      id: ip
      run: |
        echo "PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        ssh-keyscan -H $PUBLIC_IP >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deployer-key
        chmod 600 ~/.ssh/deployer-key

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deployer-key ubuntu@$PUBLIC_IP << 'EOF'
        cd /var/www/html
        sudo git clone https://github.com/${{ github.repository }}.git .
        sudo systemctl restart nginx
        EOF
